#!/usr/bin/env ruby
require_relative '../../setup'
require 'brains/both_true'

brain = BothTrue.load

def average_error(array)
  array.reduce(&:+) / array.count
end

puts "Learning"
errors = []
loop do
  begin
    errors.concat brain.train
    print "\rAverage error: #{average_error(errors).round(10)}"
  rescue SystemExit, Interrupt
    puts "Saving..."
    brain.save
    exit(0)
  end
end
